# Generated by Django 3.0.1 on 2020-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aus_Births',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aus_birth_years', models.PositiveIntegerField()),
                ('aus_births', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Australia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('australia_years', models.PositiveIntegerField()),
                ('auspop_male', models.PositiveIntegerField()),
                ('auspop_female', models.PositiveIntegerField()),
                ('auspop', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Capital_Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_years', models.PositiveIntegerField()),
                ('sydney_pop', models.PositiveIntegerField()),
                ('melbourne_pop', models.PositiveIntegerField()),
                ('brisbane_pop', models.PositiveIntegerField()),
                ('adelaide_pop', models.PositiveIntegerField()),
                ('perth_pop', models.PositiveIntegerField()),
                ('hobart_pop', models.PositiveIntegerField()),
                ('darwin_pop', models.PositiveIntegerField()),
                ('canberra_pop', models.PositiveIntegerField()),
                ('capital_cities', models.PositiveIntegerField()),
                ('rest_nsw', models.PositiveIntegerField()),
                ('rest_vic', models.PositiveIntegerField()),
                ('rest_qld', models.PositiveIntegerField()),
                ('rest_sa', models.PositiveIntegerField()),
                ('rest_wa', models.PositiveIntegerField()),
                ('rest_tas', models.PositiveIntegerField()),
                ('rest_nt', models.PositiveIntegerField()),
                ('rest_act', models.PositiveIntegerField()),
                ('rest_states', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states_years', models.PositiveIntegerField()),
                ('nsw_pop', models.PositiveIntegerField()),
                ('vic_pop', models.PositiveIntegerField()),
                ('qld_pop', models.PositiveIntegerField()),
                ('sa_pop', models.PositiveIntegerField()),
                ('wa_pop', models.PositiveIntegerField()),
                ('tas_pop', models.PositiveIntegerField()),
                ('nt_pop', models.PositiveIntegerField()),
                ('act_pop', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
