# Generated by Django 3.0.1 on 2020-01-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aus_Births',
        ),
        migrations.DeleteModel(
            name='Australia',
        ),
        migrations.DeleteModel(
            name='Capital_Cities',
        ),
        migrations.DeleteModel(
            name='States',
        ),
        migrations.DeleteModel(
            name='Years',
        ),
    ]
